### ISSUE TITLE
Little typo in the README

### ISSUE THREAD

**Issue by fowled** [zekroTJA/zekroTJA#1]
Just notifying you of a little typo in your README.

> I love playing with web technologies, creating web applications and building automatic pipelines to deploy them. I'm a huge lover of docker and linux. Mostly, I'm working with C# (.NET Core/Framework), Go and TypeScript, but I'm also **verry** experienced using stuff like Python, Java, Elixir, C++, Lua or Dart.

Should be "very" :wink:

**Comment by fowled** [comment]
Guess I'll just close it..?

**Comment by zekroTJA** [comment]
Ups, actually wanted to update it when I am not on mobile and then forgot it. Fixed it now. ^^

**Comment by fowled** [comment]
Oh alright, glad you took the time to check this. ^^
